**Setting up spark environment**

**1\. Deploy a spark cluster (Dataproc , EMR , HDInsight , on premise)**

**2.Store data in HDFS instead of local , data from Kaggle :**

[https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce](https://example.com)
#!/bin/bash
curl -L -o ~/olist/brazilian-ecommerce.zip\
  https://www.kaggle.com/api/v1/datasets/download/olistbr/brazilian-ecommerce
  
Once data is there put all the data to hadoop , not putting it right now as costing will inclrease.  
Command for same - hadoop fs -put ~/olist/data/*.csv /data/olist/

**3\. Use pyspark to interact with data.**

In [1]:
!hadoop fs -ls /data/olist/

Found 9 items
-rw-r--r--   2 geurecruitanandraj hadoop    9033957 2025-07-13 12:45 /data/olist/olist_customers_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop   61273883 2025-07-13 12:45 /data/olist/olist_geolocation_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop   15438671 2025-07-13 12:45 /data/olist/olist_order_items_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop    5777138 2025-07-13 12:45 /data/olist/olist_order_payments_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop   14451670 2025-07-13 12:45 /data/olist/olist_order_reviews_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop   17654914 2025-07-13 12:45 /data/olist/olist_orders_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop    2379446 2025-07-13 12:45 /data/olist/olist_products_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop     174703 2025-07-13 12:45 /data/olist/olist_sellers_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop       2613 2025-07-13 12:45 /data/olist/product_category_name_translation.csv

In [2]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("olistdataset").getOrCreate()

25/07/13 13:12:28 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.

In [3]:
spark

In [4]:
hdfs_path = '/data/olist/'

In [5]:
customers_df = spark.read.csv(hdfs_path+'olist_customers_dataset.csv',header=True,inferSchema=True)

In [6]:
customers_df.show()

+--------------------+--------------------+------------------------+--------------------+--------------+
|         customer_id|  customer_unique_id|customer_zip_code_prefix|       customer_city|customer_state|
+--------------------+--------------------+------------------------+--------------------+--------------+
|06b8999e2fba1a1fb...|861eff4711a542e4b...|                   14409|              franca|            SP|
|18955e83d337fd6b2...|290c77bc529b7ac93...|                    9790|sao bernardo do c...|            SP|
|4e7b3e00288586ebd...|060e732b5b29e8181...|                    1151|           sao paulo|            SP|
|b2b6027bc5c5109e5...|259dac757896d24d7...|                    8775|     mogi das cruzes|            SP|
|4f2d8ab171c80ec83...|345ecd01c38d18a90...|                   13056|            campinas|            SP|
|879864dab9bc30475...|4c93744516667ad3b...|                   89254|      jaragua do sul|            SC|
|fd826e7cf63160e53...|addec96d2e059c80c...|                    4534|           sao paulo|            SP|
|5e274e7a0c3809e14...|57b2a98a409812fe9...|                   35182|             timoteo|            MG|
|5adf08e34b2e99398...|1175e95fb47ddff9d...|                   81560|            curitiba|            PR|
|4b7139f34592b3a31...|9afe194fb833f79e3...|                   30575|      belo horizonte|            MG|
|9fb35e4ed6f0a14a4...|2a7745e1ed516b289...|                   39400|       montes claros|            MG|
|5aa9e4fdd4dfd2095...|2a46fb94aef5cbeeb...|                   20231|      rio de janeiro|            RJ|
|b2d1536598b73a9ab...|918dc87cd72cd9f6e...|                   18682|    lencois paulista|            SP|
|eabebad39a88bb6f5...|295c05e81917928d7...|                    5704|           sao paulo|            SP|
|1f1c7bf1c9b041b29...|3151a81801c838636...|                   95110|       caxias do sul|            RS|
|206f3129c0e4d7d0b...|21f748a16f4e1688a...|                   13412|          piracicaba|            SP|
|a7c125a0a07b75146...|5c2991dbd08bbf3cf...|                   22750|      rio de janeiro|            RJ|
|c5c61596a3b6bd0ce...|b6e99561fe6f34a55...|                    7124|           guarulhos|            SP|
|9b8ce803689b3562d...|7f3a72e8f988c6e73...|                    5416|           sao paulo|            SP|
|49d0ea0986edde72d...|3e6fd6b2f0d499456...|                   68485|              pacaja|            PA|
+--------------------+--------------------+------------------------+--------------------+--------------+
only showing top 20 rows

In [7]:
print(customers_df.show(5))

+--------------------+--------------------+------------------------+--------------------+--------------+
|         customer_id|  customer_unique_id|customer_zip_code_prefix|       customer_city|customer_state|
+--------------------+--------------------+------------------------+--------------------+--------------+
|06b8999e2fba1a1fb...|861eff4711a542e4b...|                   14409|              franca|            SP|
|18955e83d337fd6b2...|290c77bc529b7ac93...|                    9790|sao bernardo do c...|            SP|
|4e7b3e00288586ebd...|060e732b5b29e8181...|                    1151|           sao paulo|            SP|
|b2b6027bc5c5109e5...|259dac757896d24d7...|                    8775|     mogi das cruzes|            SP|
|4f2d8ab171c80ec83...|345ecd01c38d18a90...|                   13056|            campinas|            SP|
+--------------------+--------------------+------------------------+--------------------+--------------+
only showing top 5 rows

None

In [8]:
!hadoop fs -ls /data/olist/

Found 9 items
-rw-r--r--   2 geurecruitanandraj hadoop    9033957 2025-07-13 12:45 /data/olist/olist_customers_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop   61273883 2025-07-13 12:45 /data/olist/olist_geolocation_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop   15438671 2025-07-13 12:45 /data/olist/olist_order_items_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop    5777138 2025-07-13 12:45 /data/olist/olist_order_payments_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop   14451670 2025-07-13 12:45 /data/olist/olist_order_reviews_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop   17654914 2025-07-13 12:45 /data/olist/olist_orders_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop    2379446 2025-07-13 12:45 /data/olist/olist_products_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop     174703 2025-07-13 12:45 /data/olist/olist_sellers_dataset.csv
-rw-r--r--   2 geurecruitanandraj hadoop       2613 2025-07-13 12:45 /data/olist/product_category_name_translation.csv

In [9]:
products_df = spark.read.csv(hdfs_path+'olist_products_dataset.csv',header=True,inferSchema=True)
order_df = spark.read.csv(hdfs_path+'olist_orders_dataset.csv',header = True , inferSchema = True)
order_item_df = spark.read.csv(hdfs_path+'olist_order_items_dataset.csv',header = True, inferSchema=True)
order_payment_df = spark.read.csv(hdfs_path+'olist_order_payments_dataset.csv',header = True , inferSchema = True)
order_reviews_df = spark.read.csv(hdfs_path+'olist_order_reviews_dataset.csv',header = True , inferSchema = True)
order_location_df = spark.read.csv(hdfs_path+'olist_geolocation_dataset.csv',header = True , inferSchema = True)
seller_df = spark.read.csv(hdfs_path+'olist_sellers_dataset.csv',header = True , inferSchema = True)
ttrnaslation_df = spark.read.csv(hdfs_path+'product_category_name_translation.csv',header = True , inferSchema = True)

In [10]:
ttrnaslation_df.show(5)

+---------------------+-----------------------------+
|product_category_name|product_category_name_english|
+---------------------+-----------------------------+
|         beleza_saude|                health_beauty|
| informatica_acess...|         computers_accesso...|
|           automotivo|                         auto|
|      cama_mesa_banho|               bed_bath_table|
|     moveis_decoracao|              furniture_decor|
+---------------------+-----------------------------+
only showing top 5 rows

In [14]:
# Data Leakage check
print(f"Cutomers : {customers_df.count()} rows")
print(f"Products : {products_df.count()} rows")
print(f"Orders : {order_df.count()} rows")
print(f"Order items : {order_item_df.count()} rows")
print(f"Order payments : {order_payment_df.count()} rows")
print(f"Order Reviews: {order_reviews_df.count()} rows")
print(f"Order Loacation : {order_location_df.count()} rows")
print(f"Seller : {seller_df.count()} rows")
print(f"Category Translation : {ttrnaslation_df.count()} rows")

Cutomers : 99441 rows
Products : 32951 rows
Orders : 99441 rows
Order items : 112650 rows
Order payments : 103886 rows
Order Reviews: 104162 rows
Order Loacation : 1000163 rows
Seller : 3095 rows
Category Translation : 71 rows

In [15]:
# Checking for NULL values 
from pyspark.sql.functions import col

customers_df.select([col(c).isNull().alias(c) for c in customers_df.columns]).show()

+-----------+------------------+------------------------+-------------+--------------+
|customer_id|customer_unique_id|customer_zip_code_prefix|customer_city|customer_state|
+-----------+------------------+------------------------+-------------+--------------+
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
|      false|             false|                   false|        false|         false|
+-----------+------------------+------------------------+-------------+--------------+
only showing top 20 rows

## Exploratory data analysis on our data above data is varified through kaggle

In [17]:
from pyspark.sql.functions import col,when,count

# Check nulls for crituical columns
customers_df.select([count(when(col(c).isNull(),1)).alias(c) for c in customers_df.columns]).show()

+-----------+------------------+------------------------+-------------+--------------+
|customer_id|customer_unique_id|customer_zip_code_prefix|customer_city|customer_state|
+-----------+------------------+------------------------+-------------+--------------+
|          0|                 0|                       0|            0|             0|
+-----------+------------------+------------------------+-------------+--------------+

In [19]:
# Dupluacte values
customers_df.groupBy('customer_id').count().filter('count>1').show()

+-----------+-----+
|customer_id|count|
+-----------+-----+
+-----------+-----+

In [20]:
# Customer Distribution by state
customers_df.groupby('customer_state').count().orderBy('count',ascending= False).show()

+--------------+-----+
|customer_state|count|
+--------------+-----+
|            SP|41746|
|            RJ|12852|
|            MG|11635|
|            RS| 5466|
|            PR| 5045|
|            SC| 3637|
|            BA| 3380|
|            DF| 2140|
|            ES| 2033|
|            GO| 2020|
|            PE| 1652|
|            CE| 1336|
|            PA|  975|
|            MT|  907|
|            MA|  747|
|            MS|  715|
|            PB|  536|
|            PI|  495|
|            RN|  485|
|            AL|  413|
+--------------+-----+
only showing top 20 rows

In [21]:
# Ordres status distribution
order_df.show(5)

+--------------------+--------------------+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+
|            order_id|         customer_id|order_status|order_purchase_timestamp|  order_approved_at|order_delivered_carrier_date|order_delivered_customer_date|order_estimated_delivery_date|
+--------------------+--------------------+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+
|e481f51cbdc54678b...|9ef432eb625129730...|   delivered|     2017-10-02 10:56:33|2017-10-02 11:07:15|         2017-10-04 19:55:00|          2017-10-10 21:25:13|          2017-10-18 00:00:00|
|53cdb2fc8bc7dce0b...|b0830fb4747a6c6d2...|   delivered|     2018-07-24 20:41:37|2018-07-26 03:24:27|         2018-07-26 14:31:00|          2018-08-07 15:27:45|          2018-08-13 00:00:00|
|47770eb9100c2d0c4...|41ce2a54c0b03bf34...|   delivered|     2018-08-08 08:38:49|2018-08-08 08:55:23|         2018-08-08 13:50:00|          2018-08-17 18:06:29|          2018-09-04 00:00:00|
|949d5b44dbf5de918...|f88197465ea7920ad...|   delivered|     2017-11-18 19:28:06|2017-11-18 19:45:59|         2017-11-22 13:39:59|          2017-12-02 00:28:42|          2017-12-15 00:00:00|
|ad21c59c0840e6cb8...|8ab97904e6daea886...|   delivered|     2018-02-13 21:18:39|2018-02-13 22:20:29|         2018-02-14 19:46:34|          2018-02-16 18:17:02|          2018-02-26 00:00:00|
+--------------------+--------------------+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+
only showing top 5 rows

In [22]:
order_df.groupBy('order_status').count().orderBy('count',ascending=False).show()

+------------+-----+
|order_status|count|
+------------+-----+
|   delivered|96478|
|     shipped| 1107|
|    canceled|  625|
| unavailable|  609|
|    invoiced|  314|
|  processing|  301|
|     created|    5|
|    approved|    2|
+------------+-----+

In [23]:
# payments
order_payment_df.show(5)

+--------------------+------------------+------------+--------------------+-------------+
|            order_id|payment_sequential|payment_type|payment_installments|payment_value|
+--------------------+------------------+------------+--------------------+-------------+
|b81ef226f3fe1789b...|                 1| credit_card|                   8|        99.33|
|a9810da82917af2d9...|                 1| credit_card|                   1|        24.39|
|25e8ea4e93396b6fa...|                 1| credit_card|                   1|        65.71|
|ba78997921bbcdc13...|                 1| credit_card|                   8|       107.78|
|42fdf880ba16b47b5...|                 1| credit_card|                   2|       128.45|
+--------------------+------------------+------------+--------------------+-------------+
only showing top 5 rows

In [24]:
order_payment_df.groupBy('payment_type').count().orderBy('count',ascending = False).show()

+------------+-----+
|payment_type|count|
+------------+-----+
| credit_card|76795|
|      boleto|19784|
|     voucher| 5775|
|  debit_card| 1529|
| not_defined|    3|
+------------+-----+

In [25]:
# Find top selling product
order_item_df.show(5)

+--------------------+-------------+--------------------+--------------------+-------------------+-----+-------------+
|            order_id|order_item_id|          product_id|           seller_id|shipping_limit_date|price|freight_value|
+--------------------+-------------+--------------------+--------------------+-------------------+-----+-------------+
|00010242fe8c5a6d1...|            1|4244733e06e7ecb49...|48436dade18ac8b2b...|2017-09-19 09:45:35| 58.9|        13.29|
|00018f77f2f0320c5...|            1|e5f2d52b802189ee6...|dd7ddc04e1b6c2c61...|2017-05-03 11:05:13|239.9|        19.93|
|000229ec398224ef6...|            1|c777355d18b72b67a...|5b51032eddd242adc...|2018-01-18 14:48:30|199.0|        17.87|
|00024acbcdf0a6daa...|            1|7634da152a4610f15...|9d7a1d34a50524090...|2018-08-15 10:10:18|12.99|        12.79|
|00042b26cf59d7ce6...|            1|ac6c3623068f30de0...|df560393f3a51e745...|2017-02-13 13:57:51|199.9|        18.14|
+--------------------+-------------+--------------------+--------------------+-------------------+-----+-------------+
only showing top 5 rows

In [26]:
from pyspark.sql.functions import sum

top_products = order_item_df.groupBy('product_id').agg(sum('price').alias('total_sales'))

In [27]:
top_products.orderBy('total_sales',ascending=False).show(20)

+--------------------+------------------+
|          product_id|       total_sales|
+--------------------+------------------+
|bb50f2e236e5eea01...|           63885.0|
|6cdd53843498f9289...| 54730.20000000005|
|d6160fb7873f18409...|48899.340000000004|
|d1c427060a0f73f6b...| 47214.51000000006|
|99a4788cb24856965...|43025.560000000085|
|3dd2a17168ec895c7...| 41082.60000000005|
|25c38557cf793876c...| 38907.32000000001|
|5f504b3a1c75b73d6...|37733.899999999994|
|53b36df67ebb7c415...| 37683.42000000001|
|aca2eb7d00ea1a7b8...| 37608.90000000007|
|e0d64dcfaa3b6db5c...|          31786.82|
|d285360f29ac7fd97...|31623.809999999983|
|7a10781637204d8d1...|           30467.5|
|f1c7f353075ce59d8...|          29997.36|
|f819f0c84a64f02d3...|29024.479999999996|
|588531f8ec37e7d5f...|28291.989999999998|
|422879e10f4668299...|26577.219999999972|
|16c4e87b98a9370a9...|           25034.0|
|5a848e4ab52fd5445...|24229.029999999962|
|a62e25e09e05e6faf...|           24051.0|
+--------------------+------------------+
only showing top 20 rows

In [28]:
# Average Delivery time 
order_df.show(5)

+--------------------+--------------------+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+
|            order_id|         customer_id|order_status|order_purchase_timestamp|  order_approved_at|order_delivered_carrier_date|order_delivered_customer_date|order_estimated_delivery_date|
+--------------------+--------------------+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+
|e481f51cbdc54678b...|9ef432eb625129730...|   delivered|     2017-10-02 10:56:33|2017-10-02 11:07:15|         2017-10-04 19:55:00|          2017-10-10 21:25:13|          2017-10-18 00:00:00|
|53cdb2fc8bc7dce0b...|b0830fb4747a6c6d2...|   delivered|     2018-07-24 20:41:37|2018-07-26 03:24:27|         2018-07-26 14:31:00|          2018-08-07 15:27:45|          2018-08-13 00:00:00|
|47770eb9100c2d0c4...|41ce2a54c0b03bf34...|   delivered|     2018-08-08 08:38:49|2018-08-08 08:55:23|         2018-08-08 13:50:00|          2018-08-17 18:06:29|          2018-09-04 00:00:00|
|949d5b44dbf5de918...|f88197465ea7920ad...|   delivered|     2017-11-18 19:28:06|2017-11-18 19:45:59|         2017-11-22 13:39:59|          2017-12-02 00:28:42|          2017-12-15 00:00:00|
|ad21c59c0840e6cb8...|8ab97904e6daea886...|   delivered|     2018-02-13 21:18:39|2018-02-13 22:20:29|         2018-02-14 19:46:34|          2018-02-16 18:17:02|          2018-02-26 00:00:00|
+--------------------+--------------------+------------+------------------------+-------------------+----------------------------+-----------------------------+-----------------------------+
only showing top 5 rows

In [37]:
delivery_df = order_df.select('order_id','order_purchase_timestamp','order_delivered_carrier_date')
delivery_df.show(5)

+--------------------+------------------------+----------------------------+
|            order_id|order_purchase_timestamp|order_delivered_carrier_date|
+--------------------+------------------------+----------------------------+
|e481f51cbdc54678b...|     2017-10-02 10:56:33|         2017-10-04 19:55:00|
|53cdb2fc8bc7dce0b...|     2018-07-24 20:41:37|         2018-07-26 14:31:00|
|47770eb9100c2d0c4...|     2018-08-08 08:38:49|         2018-08-08 13:50:00|
|949d5b44dbf5de918...|     2017-11-18 19:28:06|         2017-11-22 13:39:59|
|ad21c59c0840e6cb8...|     2018-02-13 21:18:39|         2018-02-14 19:46:34|
+--------------------+------------------------+----------------------------+
only showing top 5 rows

In [38]:
from pyspark.sql.functions import datediff , to_date
delivery_detail_df = delivery_df.withColumn('delivery_time',datediff(col('order_delivered_carrier_date')\
                                                                     ,col('order_purchase_timestamp')))

In [39]:
delivery_detail_df.orderBy('delivery_time',ascending=False).show(10)

+--------------------+------------------------+----------------------------+-------------+
|            order_id|order_purchase_timestamp|order_delivered_carrier_date|delivery_time|
+--------------------+------------------------+----------------------------+-------------+
|da81fbc27b55e0f3d...|     2017-11-14 21:07:55|         2018-03-20 15:44:40|          126|
|97f48024fcc76f189...|     2017-11-29 12:25:00|         2018-03-16 13:58:02|          107|
|8b7fd198ad184563c...|     2017-11-14 10:04:27|         2018-02-26 17:27:15|          104|
|866314550f6d7a55c...|     2017-11-16 14:55:04|         2018-01-21 16:12:17|           66|
|5cc475c7c03290048...|     2016-10-04 21:54:52|         2016-12-06 17:24:00|           63|
|a4a57f1ffa25b90de...|     2017-09-06 17:07:29|         2017-11-06 20:51:56|           61|
|2805499c211b52dfc...|     2018-02-19 15:11:50|         2018-04-16 13:54:50|           56|
|2631dba338efbcea9...|     2016-10-06 08:28:19|         2016-11-30 10:53:48|           55|
|7d86c4aa9e59504b2...|     2017-01-25 16:38:10|         2017-03-21 14:40:51|           55|
|bfbd0f9bdef843021...|     2016-09-15 12:16:38|         2016-11-07 17:11:53|           53|
+--------------------+------------------------+----------------------------+-------------+
only showing top 10 rows

In [40]:
spark.stop()